const questions = [
  { q: "Which of the following best defines a business?", options: ["An organization that exists only to create social change", "An organization that provides goods or services to earn profit", "A government agency", "A group of volunteers"], answer: "B" },
  { q: "The main objective of a business is:", options: ["Social welfare only", "Profit maximization", "Employee happiness only", "Political influence"], answer: "B" },
  { q: "Which of the following is a non-profit organization?", options: ["Dangote Cement", "Red Cross", "Coca-Cola", "MTN"], answer: "B" },
  { q: "Entrepreneurship is important because it:", options: ["Reduces competition", "Creates jobs and drives economic growth", "Reduces business risks", "Eliminates taxes"], answer: "B" },
  { q: "Business environment refers to:", options: ["The physical office layout", "External and internal factors affecting a business", "Only government regulations", "Only competitors"], answer: "B" },
  { q: "Which of these is an internal factor in business environment?", options: ["Government policies", "Company culture", "Technology trends", "Social norms"], answer: "B" },
  { q: "A company’s stakeholders include:", options: ["Only owners", "Owners, employees, customers, suppliers", "Competitors only", "Tax authorities only"], answer: "B" },
  { q: "Which of the following is an example of a political factor affecting business?", options: ["Consumer tastes", "Tax policies", "Employee motivation", "Brand loyalty"], answer: "B" },
  { q: "Which of the following is a technological factor affecting business?", options: ["Government stability", "Social norms", "Automation and AI", "Employee age"], answer: "C" },
  { q: "Which of the following is NOT a component of the marketing mix?", options: ["Price", "Product", "Promotion", "Profit"], answer: "D" },
  { q: "The 4Ps of marketing include:", options: ["Product, Price, Place, Promotion", "People, Process, Physical evidence, Place", "Profit, People, Product, Process", "Product, Policy, Price, Promotion"], answer: "A" },
  { q: "Which of the following best defines consumer behavior?", options: ["The study of marketing strategies", "The study of how consumers make purchasing decisions", "The study of company policies", "The study of government regulations"], answer: "B" },
  { q: "Market segmentation involves:", options: ["Dividing the market into distinct groups of buyers", "Combining all buyers into one market", "Ignoring consumer preferences", "Reducing production costs"], answer: "A" },
  { q: "Which of the following is primary data?", options: ["Data collected from government reports", "Data collected through surveys by the company", "Data from industry journals", "Data from newspapers"], answer: "B" },
  { q: "E-commerce refers to:", options: ["Business conducted online", "Business conducted in physical stores only", "Non-profit business only", "Government-owned enterprises"], answer: "A" },
  { q: "The main purpose of financial statements is to:", options: ["Entertain investors", "Provide information for decision-making", "Reduce taxes", "Advertise products"], answer: "B" },
  { q: "Which of the following is an asset?", options: ["Bank loan", "Office building owned by the company", "Supplier debt", "Employee salary payable"], answer: "B" },
  { q: "The accounting equation is:", options: ["Assets = Liabilities + Capital", "Assets = Revenue – Expenses", "Profit = Revenue – Tax", "Assets = Revenue + Expenses"], answer: "A" },
  { q: "Which of these is a current liability?", options: ["Machinery", "Bank overdraft", "Land", "Share capital"], answer: "B" },
  { q: "The main purpose of budgeting is to:", options: ["Plan and control financial resources", "Reduce employee salaries", "Increase tax payments", "Monitor social media"], answer: "A" },
  { q: "Break-even point occurs when:", options: ["Profit = 0", "Revenue > Costs", "Costs > Revenue", "Revenue = Profit"], answer: "A" },
  { q: "Which of these is a source of long-term finance?", options: ["Bank overdraft", "Share capital", "Trade credit", "Petty cash"], answer: "B" },
  { q: "Which of the following is NOT part of supply chain management?", options: ["Procurement", "Logistics", "Marketing mix", "Production planning"], answer: "C" },
  { q: "Lean production aims to:", options: ["Reduce waste and increase efficiency", "Increase employee numbers", "Reduce product quality", "Increase production costs"], answer: "A" },
  { q: "Just-In-Time (JIT) production focuses on:", options: ["Holding large inventory", "Producing goods only when needed", "Ignoring customer demand", "Delaying production indefinitely"], answer: "B" },
  { q: "Total Quality Management (TQM) focuses on:", options: ["Reducing employee satisfaction", "Continuous improvement in quality across the organization", "Minimizing profits", "Ignoring customer feedback"], answer: "B" },
  { q: "Which of these is a function of HRM?", options: ["Budgeting only", "Recruitment and training", "Marketing only", "Production scheduling"], answer: "B" },
  { q: "Maslow’s hierarchy of needs prioritizes:", options: ["Self-actualization first", "Physiological needs first", "Social needs first", "Safety needs first"], answer: "B" },
  { q: "Herzberg’s two-factor theory divides factors into:", options: ["Leadership and Management", "Hygiene and Motivators", "Salary and Bonuses only", "Internal and External factors"], answer: "B" },
  { q: "Which of these is a form of internal recruitment?", options: ["Promoting existing staff", "Hiring from another company", "Using recruitment agencies", "Online job adverts"], answer: "A" },
  { q: "Performance appraisal is used to:", options: ["Evaluate employee performance", "Reduce wages", "Replace management", "Increase customer complaints"], answer: "A" },
  { q: "Employee retention can be improved by:", options: ["Ignoring employee needs", "Providing incentives and career growth", "Reducing training", "Increasing working hours"], answer: "B" },
  { q: "Conflict management is important because:", options: ["It creates tension", "It helps maintain workplace harmony", "It reduces productivity", "It reduces profits"], answer: "B" },
  { q: "Organizational culture refers to:", options: ["Physical buildings of the company", "Shared values, beliefs, and norms within the organization", "Employee salaries only", "Company profits only"], answer: "B" },
  { q: "Which leadership style is participative?", options: ["Autocratic", "Democratic", "Laissez-faire", "Transactional"], answer: "B" },
  { q: "Which of these is NOT part of CSR?", options: ["Charitable donations", "Environmental protection", "Employee exploitation", "Community engagement"], answer: "C" },
  { q: "Which factor affects consumer behavior?", options: ["Social, cultural, psychological, economic", "Only age and gender", "Only education", "Only government policy"], answer: "A" },
  { q: "Market research is used to:", options: ["Understand customer needs and market trends", "Increase production costs", "Reduce staff motivation", "Ignore competitors"], answer: "A" },
  { q: "A company with high liquidity can:", options: ["Easily meet short-term obligations", "Ignore debts", "Reduce revenue", "Avoid taxation"], answer: "A" },
  { q: "Which of these is a method of inventory control?", options: ["FIFO", "Pay-as-you-go", "Credit purchase", "Employee appraisal"], answer: "A" },
  { q: "Which of these is a short-term source of finance?", options: ["Bank overdraft", "Equity shares", "Debenture", "Retained earnings"], answer: "A" },
  { q: "Outsourcing in production involves:", options: ["Doing everything in-house", "Hiring external parties to handle certain activities", "Reducing employee benefits", "Increasing product defects"], answer: "B" },
  { q: "Workflow optimization improves:", options: ["Efficiency and productivity", "Product waste", "Employee stress only", "Marketing costs"], answer: "A" },
  { q: "Supply chain disruption can be caused by:", options: ["Natural disasters", "Employee motivation", "Marketing strategies", "Brand loyalty"], answer: "A" },
  { q: "Recruitment and selection ensure:", options: ["Hiring the right candidate for the right job", "Reducing employee satisfaction", "Increasing conflict", "Decreasing profits"], answer: "A" },
  { q: "Job enrichment is aimed at:", options: ["Reducing employee motivation", "Increasing job satisfaction", "Increasing company taxes", "Reducing production"], answer: "B" },
  { q: "Talent management focuses on:", options: ["Recruiting, developing, and retaining employees", "Only firing employees", "Reducing HR budget", "Ignoring employee training"], answer: "A" },
  { q: "Industrial psychology in HRM helps to:", options: ["Understand human behavior at work", "Reduce profits", "Avoid employee feedback", "Increase bureaucracy"], answer: "A" },
  { q: "Workforce planning ensures:", options: ["The right number of employees with the right skills are available", "Ignoring employee needs", "Reducing employee salaries only", "Avoiding training"], answer: "A" },
  { q: "Diversity management in organizations:", options: ["Promotes inclusion of different cultures and backgrounds", "Focuses only on one group of employees", "Ignores employee skills", "Reduces team productivity"], answer: "A" },
  { q: "Which of the following is an external factor affecting business?", options: ["Company culture", "Government policies", "Employee skills", "Management style"], answer: "B" },
  { q: "Business ethics refers to:", options: ["Laws only", "Moral principles guiding business conduct", "Employee salaries", "Marketing strategies"], answer: "B" },
  { q: "Corporate social responsibility (CSR) primarily aims to:", options: ["Increase profits only", "Benefit society while conducting business", "Reduce marketing", "Hire more employees"], answer: "B" },
  { q: "Which of these is a formal sector business?", options: ["Licensed bank", "Street hawker", "Unregistered mechanic", "Freelance artist"], answer: "A" },
  { q: "Opportunity cost is:", options: ["The cost of missing the next best alternative", "The cost of production only", "Marketing expenditure", "Employee salaries"], answer: "A" },
  { q: "Planning in business is important because it:", options: ["Reduces confusion and guides decision-making", "Increases conflicts", "Reduces profits", "Ignores competitors"], answer: "A" },
  { q: "Organizational structure defines:", options: ["How tasks and responsibilities are arranged", "Only office layout", "Employee uniforms", "Marketing campaigns"], answer: "A" },
  { q: "Line organization is characterized by:", options: ["Clear chain of command", "Flexible structure", "No reporting", "Complex hierarchy"], answer: "A" },
  { q: "Delegation involves:", options: ["Assigning responsibility to subordinates", "Ignoring staff tasks", "Hiring new employees only", "Reducing profits"], answer: "A" },
  { q: "Motivation is important because:", options: ["It improves employee performance", "It reduces profits", "It ignores HR policies", "It reduces marketing"], answer: "A" },
  { q: "Communication in business refers to:", options: ["Sharing information to achieve organizational goals", "Advertising only", "Reducing employee salaries", "Ignoring stakeholders"], answer: "A" },
  { q: "Mission statement explains:", options: ["The purpose and core values of an organization", "Employee salaries", "Marketing budget", "Warehouse layout"], answer: "A" },
  { q: "Vision statement describes:", options: ["What the organization aspires to achieve in the future", "Current profit", "HR policies", "Competitor strategy"], answer: "A" },
  { q: "Which of these is an advantage of sole proprietorship?", options: ["Easy to set up", "Unlimited liability", "Hard to dissolve", "Requires board approval"], answer: "A" },
  { q: "Which of these is a disadvantage of partnership?", options: ["Profit sharing and potential conflicts", "Single ownership", "Limited capital", "Government regulation"], answer: "A" },
  { q: "Private limited companies are characterized by:", options: ["Limited liability and shares not publicly traded", "Unlimited liability", "Shares sold on stock exchange", "No directors"], answer: "A" },
  { q: "Public limited companies can:", options: ["Sell shares to the public", "Have unlimited owners", "Avoid taxation", "Only operate locally"], answer: "A" },
  { q: "Cooperatives are:", options: ["Organizations owned and run by members for mutual benefit", "Sole proprietorships", "Only non-profit", "Government-owned"], answer: "A" },
  { q: "Privatization refers to:", options: ["Transfer of government-owned enterprises to private ownership", "Government ownership of private firms", "Reducing taxes only", "Employee layoffs"], answer: "A" },
  { q: "Globalization affects businesses by:", options: ["Increasing competition and market opportunities", "Reducing technology use", "Decreasing customer base", "Eliminating supply chains"], answer: "A" },
  { q: "Branding helps businesses by:", options: ["Creating customer recognition and loyalty", "Increasing production cost only", "Reducing marketing", "Ignoring competitors"], answer: "A" },
  { q: "Price skimming involves:", options: ["Charging a high price initially for a new product", "Reducing cost", "Long-term discounts only", "Ignoring demand"], answer: "A" },
  { q: "Place in marketing mix refers to:", options: ["Distribution strategy to get products to customers", "Office location only", "Advertising campaigns", "Employee placement"], answer: "A" },
  { q: "Promotion in marketing includes:", options: ["Advertising, sales promotion, personal selling", "Production only", "Accounting only", "HR policies"], answer: "A" },
  { q: "Social factors affecting consumer behavior include:", options: ["Family, peer groups, social class", "Company profits only", "Advertising costs", "Employee salaries"], answer: "A" },
  { q: "Psychological factors affecting consumer buying include:", options: ["Perception, motivation, learning, attitude", "Government policies", "Production cost", "Supply chain"], answer: "A" },
  { q: "Market research is important because it:", options: ["Helps understand customer needs and market trends", "Reduces inventory", "Only reduces HR costs", "Eliminates advertising"], answer: "A" },
  { q: "Cash flow differs from profit because:", options: ["Cash flow is actual inflow/outflow, profit includes non-cash items", "Profit is always equal to cash flow", "Cash flow ignores revenue", "Profit ignores expenses"], answer: "A" },
  { q: "Working capital is:", options: ["Current assets minus current liabilities", "Total assets only", "Revenue minus profit", "Cash only"], answer: "A" },
  { q: "Capital structure refers to:", options: ["Mix of debt and equity financing", "Employee hierarchy", "Production layout", "Marketing budget"], answer: "A" },
  { q: "Auditing is important because it:", options: ["Ensures accuracy and reliability of financial information", "Reduces marketing", "Reduces staff numbers", "Avoids HR responsibilities"], answer: "A" },
  { q: "Accrual accounting recognizes revenue:", options: ["When earned, not necessarily when cash is received", "Only when cash is received", "Only when expenses occur", "When salaries are paid"], answer: "A" },
  { q: "FIFO in inventory management means:", options: ["First-In, First-Out", "Fast Inventory First Order", "Fixed Item First Output", "Financial Investment First Order"], answer: "A" },
  { q: "Just-in-Time (JIT) reduces:", options: ["Inventory holding costs", "Marketing costs only", "Employee numbers only", "Production quality"], answer: "A" },
  { q: "Lean production focuses on:", options: ["Reducing waste and improving efficiency", "Increasing inventory only", "Hiring more staff only", "Ignoring customer needs"], answer: "A" },
  { q: "Supply chain resilience ensures:", options: ["Recovery from disruptions", "Only higher profits", "Reduced marketing", "Employee layoffs"], answer: "A" },
  { q: "A bottleneck in operations is:", options: ["Stage limiting overall process flow", "Excessive production", "Employee benefits", "Marketing campaign"], answer: "A" },
  { q: "Reverse logistics involves:", options: ["Returning goods from consumers to suppliers", "Forward distribution", "Inventory procurement", "Supplier management"], answer: "A" },
  { q: "ERP in business helps:", options: ["Integrate all organizational processes", "Only finance", "Only HR", "Only marketing"], answer: "A" },
  { q: "Employee turnover can be reduced by:", options: ["Training, incentives, career growth", "Reducing salaries only", "Ignoring HR policies", "Increasing work stress"], answer: "A" },
  { q: "Maslow’s self-actualization refers to:", options: ["Reaching one’s full potential", "Physiological needs", "Social needs", "Safety needs"], answer: "A" },
  { q: "Herzberg’s motivators include:", options: ["Achievement, recognition, responsibility", "Company policies only", "Salary only", "Job security only"], answer: "A" },
  { q: "Succession planning ensures:", options: ["Smooth leadership transition", "Hiring external candidates only", "Reducing profits", "Marketing growth"], answer: "A" },
  { q: "Diversity management in organizations ensures:", options: ["Inclusion of different cultural backgrounds", "Uniform employee culture only", "Exclusion policies", "Reducing skills"], answer: "A" },
  { q: "Conflict management helps to:", options: ["Reduce workplace tension and maintain productivity", "Increase disputes", "Ignore employee complaints", "Reduce customer satisfaction"], answer: "A" },
  { q: "Performance appraisal evaluates:", options: ["Employee efficiency and effectiveness", "Marketing campaigns only", "Production cost only", "Supplier relationships"], answer: "A" },
  { q: "Job enrichment aims to:", options: ["Increase job satisfaction", "Reduce work quality", "Increase employee stress", "Reduce company profits"], answer: "A" },
  { q: "Talent management includes:", options: ["Recruiting, developing, and retaining employees", "Ignoring training", "Reducing workforce", "Outsourcing only"], answer: "A" },
  { q: "Workforce planning ensures:", options: ["Right people with right skills at right time", "Ignoring employee needs", "Reducing HR budget", "Avoiding training"], answer: "A" },
  { q: "Ethical behavior in HRM promotes:", options: ["Trust, fairness, and transparency", "Employee exploitation", "Reducing employee rights", "Ignoring workplace laws"], answer: "A" },
  { q: "Which of the following is a component of the business environment?", options: ["Technology", "Employee salary only", "Marketing budget only", "Advertising campaign"], answer: "A" },
  { q: "Social responsibility in business involves:", options: ["Acting in ways that benefit society", "Ignoring customers", "Reducing production", "Reducing employee benefits"], answer: "A" },
  { q: "An example of internal business environment factor is:", options: ["Company policies", "Government regulations", "Competitor behavior", "Tax policy"], answer: "A" },
  { q: "External factors affecting business include:", options: ["Political, economic, social, technological", "Only company rules", "Employee morale", "Internal training programs"], answer: "A" },
  { q: "Profit maximization focuses on:", options: ["Earning the highest possible financial returns", "Reducing employee satisfaction", "Ignoring customer needs", "Only marketing"], answer: "A" },
  { q: "Which of the following is a function of management?", options: ["Planning, organizing, leading, controlling", "Advertising only", "Employee salary payment", "Inventory management only"], answer: "A" },
  { q: "Decision-making in business involves:", options: ["Selecting the best course of action among alternatives", "Ignoring problems", "Reducing profits", "Increasing employee stress"], answer: "A" },
  { q: "Leadership is important because:", options: ["It guides and motivates employees to achieve goals", "It reduces marketing", "It increases taxes", "It eliminates profits"], answer: "A" },
  { q: "Line and staff organization differ because:", options: ["Staff provides advice, line has direct authority", "Staff does production, line does HR only", "Staff handles marketing only", "Line avoids responsibilities"], answer: "A" },
  { q: "Motivation theory by Maslow is called:", options: ["Hierarchy of needs", "Two-factor theory", "Expectancy theory", "Equity theory"], answer: "A" },
  { q: "Herzberg’s hygiene factors include:", options: ["Salary, company policy, working conditions", "Recognition, achievement", "Promotion opportunities", "Job enrichment only"], answer: "A" },
  { q: "Employee training improves:", options: ["Knowledge and skills", "Inventory only", "Marketing campaigns", "Production cost only"], answer: "A" },
  { q: "Recruitment ensures:", options: ["Hiring the right candidate", "Ignoring staff needs", "Reducing salaries", "Increasing conflicts"], answer: "A" },
  { q: "Organizational culture is:", options: ["Shared values and norms in the workplace", "Employee uniforms only", "Office layout only", "Advertising strategy"], answer: "A" },
  { q: "Conflict in organizations can be managed by:", options: ["Mediation and negotiation", "Ignoring employees", "Reducing marketing", "Increasing inventory"], answer: "A" },
  { q: "Supply chain management integrates:", options: ["Suppliers, manufacturers, distributors, and customers", "HR policies only", "Marketing only", "Finance only"], answer: "A" },
  { q: "Push supply chain is based on:", options: ["Forecasted demand", "Actual demand", "Customer orders only", "Supplier choice only"], answer: "A" },
  { q: "Pull supply chain relies on:", options: ["Customer demand", "Forecast only", "Supplier contracts only", "Inventory levels only"], answer: "A" },
  { q: "Hybrid push-pull strategy is used to:", options: ["Balance forecasted and actual demand", "Ignore inventory", "Reduce marketing", "Increase bureaucracy"], answer: "A" },
  { q: "Inventory management aims to:", options: ["Maintain optimal stock levels and reduce costs", "Increase storage only", "Ignore production", "Reduce customer satisfaction"], answer: "A" },
  { q: "Safety stock is maintained to:", options: ["Prevent stockouts during demand fluctuations", "Increase production cost", "Reduce employee motivation", "Ignore customer needs"], answer: "A" },
  { q: "Just-in-Time (JIT) inventory system:", options: ["Minimizes stock and delivers goods as needed", "Increases excess inventory", "Ignores customer orders", "Reduces production efficiency"], answer: "A" },
  { q: "Lean production reduces:", options: ["Waste and unnecessary costs", "Product quality", "Employee salaries only", "Marketing budgets only"], answer: "A" },
  { q: "Total Quality Management (TQM) ensures:", options: ["Continuous improvement in products and services", "Employee layoffs", "Increased production cost", "Reduced inventory"], answer: "A" },
  { q: "Bullwhip effect occurs when:", options: ["Demand fluctuations are amplified upstream", "Inventory is stable", "Production is slow", "Customer orders are ignored"], answer: "A" },
  { q: "Supplier relationship management focuses on:", options: ["Building strong partnerships for efficiency", "Ignoring suppliers", "Increasing production cost", "Reducing profits"], answer: "A" },
  { q: "Cross-docking helps to:", options: ["Reduce warehouse storage time", "Increase inventory holding", "Reduce customer satisfaction", "Increase production errors"], answer: "A" },
  { q: "Transportation in supply chain is important because:", options: ["It connects suppliers, manufacturers, and customers efficiently", "It reduces advertising only", "It manages employee salaries only", "It ignores customer demand"], answer: "A" },
  { q: "Lead time is:", options: ["Time between ordering and receiving goods", "Marketing duration", "Employee training time", "Production cost only"], answer: "A" },
  { q: "Cycle stock is:", options: ["Inventory used to meet normal demand", "Safety stock", "Marketing budget", "Employee salary fund"], answer: "A" },
  { q: "Reverse logistics refers to:", options: ["Returning products from customers back to suppliers", "Forward delivery only", "Production scheduling", "Marketing only"], answer: "A" },
  { q: "Supplier diversification helps to:", options: ["Reduce supply chain risk", "Increase lead time", "Reduce quality", "Reduce production efficiency"], answer: "A" },
  { q: "ERP systems help organizations to:", options: ["Integrate all processes across departments", "Reduce customer orders", "Increase inventory waste", "Avoid employee training"], answer: "A" },
  { q: "Key performance indicators (KPIs) in supply chain include:", options: ["Delivery accuracy, inventory turnover, lead time", "Employee birthdays only", "Marketing budget only", "Office size only"], answer: "A" },
  { q: "Risk management in supply chain ensures:", options: ["Minimization and mitigation of potential disruptions", "Ignoring suppliers", "Increased production costs only", "Reducing customer satisfaction"], answer: "A" },
  { q: "Outsourcing in production helps to:", options: ["Reduce costs and focus on core competencies", "Increase internal production only", "Ignore quality", "Reduce employee skills"], answer: "A" },
  { q: "Performance appraisal is used to:", options: ["Evaluate employee contribution to organizational goals", "Reduce salaries only", "Ignore HR policies", "Increase conflicts"], answer: "A" },
  { q: "Job enrichment improves:", options: ["Employee motivation and satisfaction", "Production errors", "Marketing only", "Inventory costs"], answer: "A" },
  { q: "Talent management includes:", options: ["Recruiting, training, and retaining top talent", "Ignoring employees", "Reducing HR budgets only", "Outsourcing all roles"], answer: "A" },
  { q: "Succession planning ensures:", options: ["Smooth transition in leadership", "Ignoring promotions", "Reducing profits", "Increasing inventory"], answer: "A" },
  { q: "Maslow’s hierarchy of needs starts with:", options: ["Physiological needs", "Self-actualization", "Social needs", "Esteem needs"], answer: "A" },
  { q: "Herzberg’s motivators include:", options: ["Recognition, responsibility, advancement", "Salary only", "Company policies only", "Job security only"], answer: "A" },
  { q: "Organizational culture affects:", options: ["Employee behavior and productivity", "Marketing only", "Production cost only", "Inventory only"], answer: "A" },
  { q: "Diversity management ensures:", options: ["Inclusion of employees from different backgrounds", "Uniform employee culture only", "Reduces innovation", "Reduces productivity"], answer: "A" },
  { q: "Ethical behavior in HRM promotes:", options: ["Fairness, transparency, and trust", "Employee exploitation", "Ignoring labor laws", "Reduced profits"], answer: "A" },
  { q: "Workforce planning ensures:", options: ["Right number of employees with right skills at the right time", "Ignoring training needs", "Reducing staff only", "Avoiding recruitment"], answer: "A" },
  { q: "Conflict management helps to:", options: ["Maintain workplace harmony and productivity", "Increase disputes", "Reduce customer satisfaction", "Ignore problems"], answer: "A" },
  { q: "Employee retention is improved by:", options: ["Providing incentives, training, and growth opportunities", "Reducing salaries only", "Ignoring staff needs", "Increasing workload"], answer: "A" },
  { q: "Leadership style that involves employees in decision-making is:", options: ["Democratic", "Autocratic", "Laissez-faire", "Transactional"], answer: "A" },
  { q: "Organizational structure defines:", options: ["Hierarchy, roles, and responsibilities", "Only office layout", "Marketing strategy", "Inventory"], answer: "A" },
  { q: "Delegation involves:", options: ["Assigning tasks and authority to subordinates", "Ignoring staff", "Hiring more staff only", "Reducing profits"], answer: "A" },
  { q: "Business ethics ensures:", options: ["Moral and fair conduct in business", "Profit only focus", "Employee exploitation", "Ignoring customers"], answer: "A" },
  { q: "CSR helps organizations:", options: ["Benefit society while operating sustainably", "Reduce marketing only", "Increase profits at any cost", "Ignore employees"], answer: "A" },
  { q: "Opportunity cost is:", options: ["Value of the next best alternative foregone", "Only financial cost", "Salary only", "Production cost only"], answer: "A" }
];
